# Generated by Django 2.0.7 on 2018-08-10 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20180810_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coproperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Name')),
                ('Address', models.CharField(blank=True, max_length=80, null=True, verbose_name='Address')),
                ('Phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
                ('Active', models.BooleanField(default=True, verbose_name='Active')),
                ('CreateDate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('Icon', models.ImageField(blank=True, help_text='300x300', max_length=255, null=True, upload_to='icon/CopropertyImage/')),
                ('City', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Cities', verbose_name='Coproperty City')),
                ('Country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Country', verbose_name='Coproperty Country')),
                ('Manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserManagerCoproperty', to=settings.AUTH_USER_MODEL, verbose_name='User Manager')),
                ('UserCreate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserCreateCoproperty', to=settings.AUTH_USER_MODEL, verbose_name='Users Create')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=80, verbose_name='Code')),
                ('Active', models.BooleanField(default=True, verbose_name='Active')),
                ('CreateDate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('Icon', models.ImageField(blank=True, help_text='300x300', max_length=255, null=True, upload_to='icon/PropertyImage/')),
                ('Coproperty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coproperties.Coproperty', verbose_name='Coproperty')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Principal', models.BooleanField(default=False, verbose_name='Principal')),
                ('Phone', models.BigIntegerField(verbose_name='Phone')),
                ('Active', models.BooleanField(default=True, verbose_name='Active')),
                ('CreateDate', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('Icon', models.ImageField(blank=True, help_text='300x300', max_length=255, null=True, upload_to='icon/PropertyImage/')),
                ('Property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coproperties.Property', verbose_name='Property')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PropertyPhoneUsers', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
                ('UserCreate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserCreatePropertyPhone', to=settings.AUTH_USER_MODEL, verbose_name='Users Create')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='User',
            field=models.ManyToManyField(related_name='PropertyUsers', through='coproperties.PropertyPhones', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AddField(
            model_name='property',
            name='UserCreate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserCreateProperty', to=settings.AUTH_USER_MODEL, verbose_name='Users Create'),
        ),
    ]
