# Generated by Django 2.0.7 on 2018-08-10 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Country Name')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Country Description')),
                ('Icon', models.ImageField(blank=True, help_text='300x300', max_length=255, null=True, upload_to='icon/CountryImages/', verbose_name='Country Image')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='Country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Country', verbose_name='Users Country'),
        ),
    ]
